config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :participations
  resources :events
  resources :users
  resources :charges
  root to: 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participation.rb
class Participation < ApplicationRecord
    belongs_to :event 
    belongs_to :attendee, class_name: "User"

    after_create :new_attendee

    def new_attendee
        AttendeeMailer.attendee_email(self.attendee, self.event).deliver_now
    end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: [:show, :edit, :update, :destroy]

  # GET /participations
  # GET /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1
  # GET /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  def subscribe
    if 
      @event.attendees.include? current_user
      flash[:error] = "Vous participez déjà à l'événement"
      redirect_to @event
    else
      @event.attendees << current_user
        flash[:success] = "Vous participez à l'événement"
      redirect_to @event
    end

  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  # POST /participations.json
  def create

    @event = Event.find(params[:event_id ])

    if  @event.attendees.include? current_user
      flash[:error] = "Vous participez déjà à l'événement"
      redirect_to @event
      return
    end

    @amount = @event.price
    
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @event.price,
      description: 'Paiement de #{@user.first_name, @user.last_name}',
      currency: 'eur',
    })

    @participation.update(stripe_customer_id: customer.id)


    @event.attendees << current_user
        flash[:success] = "Vous participez à l'événement"
      redirect_to @event
    
    @participation = Participation.create(event_id: @event.id, attendee_id: current_user.id, stripe_customer_id: customer.id)

    puts "§§§§§§§§§§§§§§§§§§#{customer.id}§§§§§§§§§§§§§§§§§§§§§§§§§§§"

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path

  end

  # PATCH/PUT /participations/1
  # PATCH/PUT /participations/1.json
  def update
    respond_to do |format|

      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: 'Participation was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: 'Participation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      params.require(:participation).permit(:stripe_customer_id, :event_id, :attendee_id)
    end

end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_with(model: participation, local: true) do |form| %>
  <% if participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

<% end %>

app/views/participations/edit.html.erb
<h1>Editing Participation</h1>

<%= render 'form', participation: @participation %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-hero">
  <div class='container'>
    <div class="text-center">
    <br>
    <h1>Participations<h1>
    </div>
    <br>
    <br>
    <div class="text-center">
      <div class="d-flex justify-content-center">

      <p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Stripe customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= participation.stripe_customer_id %></td>
        <td><%= link_to 'Show', participation %></td>
        <td><%= link_to 'Edit', edit_participation_path(participation) %></td>
        <td><%= link_to 'Destroy', participation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participation', new_participation_path %>


      
    
      </div>
    </div>
  </div>
</div>

app/views/participations/new.html.erb
<h1>New Participation</h1>


<%= link_to 'Back', events_path %>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stripe customer:</strong>
  <%= @participation.stripe_customer_id %>
</p>

<%= link_to 'Edit', edit_participation_path(@participation) %> |
<%= link_to 'Back', participations_path %>