config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :participations
  resources :events
  resources :users
  resources :charges
  root to: 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

    validates :start_date, presence: true
    validate :start_must_be_future
    validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 } 
    validate :duration_must_be_multiple_of_5
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price, presence: true, length: { in: 1..1000 }
    validates :location, presence: true

    belongs_to :organisator, class_name: "User"
    has_many :participations, dependent: :destroy
    has_many :attendees, through: :participations, class_name: "User" 


    private

    #Valider que la date de début est bien dans le futur

  def start_must_be_future
    return if start_date.blank? #On sort de la boucle si start_date est vide
    
    if start_date < Time.now
      errors.add(:start_date, "cannot be past")
    end
  end

  #Duration is multiple of 5
  def duration_must_be_multiple_of_5
    return if duration.blank? #On sort si la fonction est vide

    if duration % 5 != 0
      errors.add(:duration, "Duration has to be multiple of 5")
    end

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:update, :edit, :update, :destroy]
  before_action :check_user, only: [ :update, :edit, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params 
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :organisator_id)
    end

    def check_user
        unless current_user == @event.organisator
          flash[:danger] = "You need to be the organisator of the event to make any modification"
          redirect_to events_path
        end
    end
  


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, class:'form-control rounded-pill' %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control rounded-pill' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:'form-control rounded-pill' %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, class:'form-control rounded-pill' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class:'form-control rounded-pill' %>
    <br>
  </div>

  <%= form.hidden_field :organisator_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/events/edit.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-hero">
  <div class='container'>
    <div class="text-center">
    <br>
    <h1>Editing Event<h1>
    </div>
    <br>
    <br>
    <div class="text-center">
      <div class="d-flex justify-content-center">
        <%= render 'form', event: @event %>

        <%= link_to 'Show', @event %> |
        <%= link_to 'Back', events_path %>
      
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-hero">
  <div class='container'>
    <div class="text-center">
    <br>
    <h1>Events<h1>
    </div>
    <br>
    <br>
    <div class="text-center">

      <p id="notice"><%= notice %></p>
          <div class='container'>
          <div class="card-columns">
            <% @events.each do |event| %>
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><%= event.title %></h5>
                  <p class="card-text"><%= event.description %><%= event.start_date %><%= event.duration %><%= event.price %><%= event.location %></p>
                  <p> <%= link_to 'Show', event, class:'btn btn-primary' %>
                  <% if current_user == event.organisator %>
                  <%= link_to 'Edit', edit_event_path(event), class:'btn btn-2' %>
                  <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-4' %></p>
                  <% end %>
                </div>
              </div>
              <% end %>
          </div>
          </div>  
          <br>    
      
    </div>
  </div>
</div>


  

app/views/events/new.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-hero">
  <div class='container'>
    <div class="text-center">
    <br>
    <h1>New Event<h1>
    </div>
    <br>
    <br>
    <div class="text-center">
      <div class="d-flex justify-content-center">
        <%= render 'form', event: @event %>      
      </div>
      <br>
      <%= link_to 'Back', events_path, class:'btn btn-3 rounded-pill'  %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-hero">
  <div class='container'>
    <div class="text-center">
    <br>
    <h1>Event<h1>
    </div>
    <br>
    <br>
    <div class="text-center">
      <div class="d-flex justify-content-center">
        <p id="notice"><%= notice %></p>
        <img src="/assets/BackToDuck.jpg" class="card-img-top imgBorder" alt="Halla Bien">
        <p id="notice"><%= notice %></p>
        <div class='container'>
          <div class="card-columns">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><%= @event.title %></h5>
                  <p class="card-text"> </p>
                  <p <%= @event.description %></p>
                  <p <%= @event.start_date %></p>
                  <p <%= @event.duration %></p> 
                  <p <%= @event.price %></p>
                  <p <%= @event.location %></p>
                  <p <%= link_to 'Show', @event, class:'btn btn-primary' %></p>
                  <% if current_user == @event.organisator %>
                  <p <%= link_to 'Edit', edit_event_path(@event), class:'btn btn-2' %></p>
                  <p <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-4' %></p>
                  <% end %>
              </div>

            
              
              <%= form_tag participations_path, method: "post" do %>

                <article>
                
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  <label class="amount">
                    <span>Amount: <%= @event.price.to_f / 100 %>€</span>
                  </label>
                </article>



              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Paiement <%= @event.title %>"
              data-amount="<%= @event.price %>"
              data-locale="auto">
              </script>
              <input name="event_id" value="<%= @event.id %>" type="hidden">
              <input name="attendee_id" value="<%= current_user.id %>" type="hidden">


              <% end %>
                
            </div>
                
          </div>
        </div>  

        <%= link_to 'Edit', edit_event_path(@event) %> 
        <%= link_to 'Back', events_path %>
        
      </div>
    </div>
  </div>
</div>