config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :participations
  resources :events
  resources :users
  resources :charges
  root to: 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Halla Bien</title>
    <link rel="icon" type="image/png" href="/assets/H.png">
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/8813a93217.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Anton|Staatliches|Varela+Round&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
  </head>

  <body>  
  <div class="d-flex flex-column flex-md-row align-items-center px-md-4 bg-white">
    <a class="mr-md-auto navbar-brand" href="<%= root_path %>" title="Home"><img style="max-width:50px;" src="/assets/H.png"></a>
    
    <nav class="my-2 my-md-0 mr-md-10">
        <a href="<%= events_path %>" class ="btn btn-outline rounded-pill">Home</a>
        <a href="<%= new_event_path %>" class ="btn btn-outline rounded-pill">New Event</a>
        
      <button class="btn btn-outline-dark rounded-pill dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Menu
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <% if user_signed_in? %>
        <a href="<%= edit_user_path(current_user.id) %>" class="dropdown-item">Edit Profile</a>
        <%= link_to "Edit email / password", edit_user_registration_path %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
        <% else %>
        <a href="<%= new_user_session_path %>" class="dropdown-item">Log in</a>
        <a href="<%= new_user_registration_path %>" class="dropdown-item">Sign Up</a>
        <% end %>
      </div>

    </nav>
  </div>
  <%= yield %>
  
  <div style="text-align: center; font-size: 20px">
  <footer class="container">
      <div class="row">
          <div class="col-12 col-md">
              <small class="d-block mb-3 text-grey">Copyright © 2019 Halla Bien. All rights reserved.</small>
          </div>
      </div>
  </footer>
  </div>
  </body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>